# Generated by Django 4.2.7 on 2024-01-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogs', '0002_alter_dog_birthday_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='app_dogs.breed', verbose_name='порода'),
        ),
    ]
