# Generated by Django 4.2.7 on 2024-02-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogs', '0004_dog_is_public_dog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='цена'),
        ),
    ]
