# Generated by Django 4.2.7 on 2024-02-29 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dogs', '0006_dog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки'),
        ),
    ]
