version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=drf_practice_dogs
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '54321:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8080
    ports:
      - '8081:8080'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
